### PR TITLE
WIP: Fail build on failing tests

### LINKED ISSUE #48: Failing tests don't fail the build
When fixing #25 I noticed that one of the tests was failing on python 3 due to a change in
the interface of the string function `translate` [1]. I fixed that, but then noticed that the builds
on travis where passing all along. It seems that coverage does not fail the build on failing tests.
Is that intentional?

If not, it might be possible to run codecov with the `--required` option making it exit with *-1* when it 
fails [2]. Otherwise it would be necessary to run the test with a separate test runner.

[1] https://travis-ci.org/kisom/pypcapfile/jobs/309041427
[2] https://github.com/codecov/codecov-python/blob/0743daa83647f12ff31b84d07113d2c24c27b924/codecov/__init__.py#L213

### PR DESCRIPTION
**Pull request by Don42**
This is work in progress, but since the change only shows in CI I created this PR.

Fixes #48

### CODE REVIEW

**Comment by Don42** [comment]
The good news, builds now fail on test failures.
The bad news, tests on PyPy have been failing for quite a while. I'm still unsure what the root cause for that is.

[1] https://travis-ci.org/kisom/pypcapfile/jobs/156608786

**Comment by kisom** [comment]
Looking at the error messages, I think that pypy is trying to do a buffered read on the savefile, and therefore it's not actually reading the header. I can try to fix this later.

**Comment by Don42** [comment]
If found the issue. Pypy does not write to the file when it is not properly closed.
I got a fix and will add that now.

**Comment by kisom** [comment]
Thanks again, @Don42!

**Pull request merged**
