### PR TITLE
Added an option for reading packets lazily.

### PR DESCRIPTION
**Pull request by tommyolofsson**
We had problems with running out of memory when working with huge captures.

### CODE REVIEW

**Comment by kisom** [comment]
Can you write a test for the new function, and add your name to the AUTHORS file?

**Comment by tommyolofsson** [comment]
All good?

**Comment by kisom** [comment]
Looks good to me, thanks!

**Comment by kisom** [comment]
Just a follow up, I've pushed version [0.11](https://github.com/kisom/pypcapfile/tree/0.11) (incorporating this and some other changes) to pypi.

**Comment by tommyolofsson** [comment]
Awesome!

**Pull request merged**
