### PR TITLE
Wi-Fi Support

### PR DESCRIPTION
**Pull request by kivanccakmak**
Hi there,

I added partially parsing for Wi-Fi packets, to use library with "wirelessly" sniffed data.
Data packet and most frequently used control packets (RTS, CTS and acknowledgements) is detailly added now. For others, only identifying is handled.

### CODE REVIEW

**Comment by kisom** [comment]
@kivanccakmak There are merge conflicts with this (and it appears there are no tests). Can you clean up the merge conflicts, squash the commits, and add tests? Thanks!

**Comment by kivanccakmak** [comment]
@kisom sure, I would.

**Comment by kivanccakmak** [comment]
@kisom I added unit tests and run, also solved conflicts. Nevertheless, something fails on Travis CI and I can't observe it, the link does not open on my PC. Also, how shall I squash commits, since I pushed them on my forked repo. Shall I create new pull request with single commit and all existing (and non conflicting:) changes? Thanks.

**Comment by kisom** [comment]
Obsoleted by #23.

**Pull request closed without merging**
